#### **Case Study - 1:** ```CrossValidation (Medical insurance)```

##### **Flow:**
```py
       Dataset
         |
    Train / Test Split
         |
    Model Selection
         |
    GridSearchCV
         |
    Kfold Cross Validation
         |
    Best Hyperparameters
         |
    Train Final Model
         |
    Test Accuracy
```

In [ ]:
#Importing necessary libraries
import pandas as pd
import numpy as np

In [2]:
#Reading the CSV data
df = pd.read_csv(r'C:\Users\raksh\OneDrive\Documents\Data-Science-AIML-Portfolio\Machine Learning\Datasets\insurance.csv')

In [3]:
#display of data
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

Ideal first 3 thumb rule in initial checks:
- No null values
- data types should be as intent(every feature should be numeric).
- No outliers.

In [4]:
#To understand more about the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [5]:
#Checking for null values that gives how many null are present for each column.
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

- We can conclude that our dataset doesn't have any null values.

In [6]:
#To understand more statitically of our data.
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [7]:
#We are converting our categorical values into numeric patterns. We can do labelEncoder.
dum_df = pd.get_dummies(df, drop_first=True)

In [8]:
#We are dividing the data into Feature variables and target variables.
X = dum_df.drop("charges", axis=1)
y = dum_df['charges']

#### ```Linear Regression with Polynomial Features```

In [ ]:
#Importing necessary libraries for model selection and feature extraction.
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [10]:
#We are creating an object for our polynomial features with Degree = 2
poly = PolynomialFeatures(degree=2)

In [11]:
X_poly = poly.fit_transform(X)

In [12]:
#We are importing train test split library
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X_poly,y, test_size=0.3, random_state=2026)

In [14]:
#Defining a regressor object for our model
regressor = LinearRegression()

In [15]:
#Training our data to our LR model.
regressor.fit(X_train,y_train)

LinearRegression()

In [16]:
#We are predicting on our X_test data
y_pred = regressor.predict(X_test)

In [17]:
#We will look into the M = Co-efficient our alogorithm.
print(regressor.coef_)

[-2.57172083e-08 -6.91623720e+01  5.18587096e+02  6.37657225e+02
 -4.94432532e+02 -1.05405793e+04 -1.28949770e+02  1.26329102e+03
  3.58446140e+02  3.42344526e+00  6.61531149e-01 -5.75216778e-01
  1.76482005e+01  9.22854915e+00 -2.65741334e+00  5.37753938e+01
  3.79484357e+01 -7.95363734e+00  2.00947882e+01  1.82142418e+01
  1.46630642e+03  1.10295725e+01 -1.40798773e+02 -9.22369668e+01
  9.68476604e+00 -3.42910277e+02 -3.66965849e+02  3.55008902e+00
 -5.38094507e+02 -6.61202468e+02 -4.94432532e+02  3.23728155e+02
 -6.77130296e+02 -3.41683722e+02  1.68001513e+01 -1.05405793e+04
  1.51628151e+02 -1.07313923e+03  4.38532486e+02 -1.28949770e+02
  0.00000000e+00  0.00000000e+00  1.26329102e+03  0.00000000e+00
  3.58446140e+02]

In [18]:
#We will look for C = intercept of our algorithm.
print(regressor.intercept_)

-4465.0463576114125

In [19]:
#Importing our metrics library.
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

In [20]:
#Importing mean_squared_error, mean_absolute_error, r2_Score from sklearn.metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#printing Mean Squared Error (MSE)
print("MSE -->",np.sqrt(mean_squared_error(y_test, y_pred)))

#Printing Mean Absolute Error (MAE)
print("MAE -->",mean_absolute_error(y_test, y_pred))

#Printing R2 Score
print("R2 Score -->",r2_score(y_test, y_pred))

MSE --> 4720.231368834211
MAE --> 2828.2874038115906
R2 Score --> 0.8607049706338095

#### ```Using K-Fold Cross Validation```

In [21]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [32]:
#We are defining our KFold to be split in 5 folds, and shuffle data.
kfold = KFold(n_splits=5, random_state=2026, shuffle=True)

In [33]:
#Apply the regressor and calculating result using cross_val_score() method and setting CV=kfold, scoring = 'r2'
results = cross_val_score(regressor, X, y, cv=kfold, scoring='r2')

In [34]:
#Assigning a variable R2 to the result.
R2 = results

In [35]:
#Printing R2score for 5 folds
print(R2)

[0.76371437 0.73362123 0.74494164 0.71369991 0.77150821]

In [36]:
#Printing mean of R2 Score
print("R-Squared: %.2f"%(R2.mean()))

R-Squared: 0.75

- This is not a quite a good R2 score we have got

#### ```GridSearch with Respect to LASSO Regression on Polynomial Features```

In [39]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV

In [40]:
#We are creating a parameter variable for our alpha in dict format
parameters = dict(alpha=[0,0.001, 0.1, 0.5, 0.8, 1, 1.5, 2])

In [41]:
#We are creating our object Lasso() algo.
clf = Lasso()

- Here we will use Polynomial features with Lasso with respect to KFold GridSearch

In [42]:
#We are defining our KFold parameters to split data.
kfold = KFold(n_splits= 5, shuffle=True, random_state=2022)

In [ ]:
#Creating an object for GridSearchCV with Lasso, parameters that defined above, with folds in cv. Scoring based on R2.
cv = GridSearchCV(estimator=clf, param_grid=parameters, scoring='r2', cv=kfold)

In [55]:
#Split with polynomial feature training data.
cv.fit(X_poly, y)

c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.266e+10, tolerance: 1.575e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.121e+10, tolerance: 1.511e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.103e+10, tolerance: 1.612e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.282e+10, tolerance: 1.648e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.153e+10, tolerance: 1.496e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.262e+10, tolerance: 1.575e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.118e+10, tolerance: 1.511e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.099e+10, tolerance: 1.612e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.268e+10, tolerance: 1.648e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.149e+10, tolerance: 1.496e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.261e+10, tolerance: 1.575e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.114e+10, tolerance: 1.511e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.099e+10, tolerance: 1.612e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.272e+10, tolerance: 1.648e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.149e+10, tolerance: 1.496e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.258e+10, tolerance: 1.575e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.106e+10, tolerance: 1.511e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.093e+10, tolerance: 1.612e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.262e+10, tolerance: 1.648e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.145e+10, tolerance: 1.496e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.259e+10, tolerance: 1.575e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.111e+10, tolerance: 1.511e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.088e+10, tolerance: 1.612e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.264e+10, tolerance: 1.648e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.147e+10, tolerance: 1.496e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.260e+10, tolerance: 1.575e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.110e+10, tolerance: 1.511e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.089e+10, tolerance: 1.612e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.265e+10, tolerance: 1.648e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.148e+10, tolerance: 1.496e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.262e+10, tolerance: 1.575e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.111e+10, tolerance: 1.511e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.092e+10, tolerance: 1.612e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.266e+10, tolerance: 1.648e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.148e+10, tolerance: 1.496e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.250e+10, tolerance: 1.575e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.086e+10, tolerance: 1.511e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.091e+10, tolerance: 1.612e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.264e+10, tolerance: 1.648e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.109e+10, tolerance: 1.496e+07
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.473e+10, tolerance: 1.961e+07
  model = cd_fast.enet_coordinate_descent(

GridSearchCV(cv=KFold(n_splits=5, random_state=2022, shuffle=True),
             estimator=Lasso(),
             param_grid={'alpha': [0, 0.001, 0.1, 0.5, 0.8, 1, 1.5, 2]},
             scoring='r2')

In [56]:
#we are storing into Dataframe.
df_cv = pd.DataFrame(cv.cv_results_)

In [57]:
df_cv

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.016248,0.001281,0.000878,0.000219,0.000,{'alpha': 0},0.877321,0.827779,0.765382,0.861127,0.848343,0.835990,0.038848,8
1,0.015356,0.000430,0.000678,0.000203,0.001,{'alpha': 0.001},0.877321,0.827779,0.765382,0.861127,0.848343,0.835990,0.038848,7
2,0.014986,0.001137,0.000784,0.000094,0.100,{'alpha': 0.1},0.877358,0.827821,0.765419,0.861145,0.848337,0.836016,0.038842,6
3,0.009871,0.000817,0.000528,0.000221,0.500,{'alpha': 0.5},0.877613,0.827999,0.765557,0.861303,0.848401,0.836175,0.038863,5
4,0.010832,0.001115,0.000741,0.000098,0.800,{'alpha': 0.8},0.877761,0.828116,0.765618,0.861405,0.848433,0.836267,0.038883,4
5,0.011154,0.000256,0.000689,0.000081,1.000,{'alpha': 1},0.877859,0.828172,0.765675,0.861460,0.848454,0.836324,0.038889,3
6,0.012170,0.001155,0.000833,0.000222,1.500,{'alpha': 1.5},0.878048,0.828289,0.765818,0.861593,0.848523,0.836454,0.038894,2
7,0.011280,0.000720,0.000680,0.000165,2.000,{'alpha': 2},0.878207,0.828421,0.765938,0.861725,0.848768,0.836612,0.038911,1

In [58]:
print("Lasso with Poly Features:")
print("Best_params: ", cv.best_params_)
print("Best Score: ", cv.best_score_)

Lasso with Poly Features:
Best_params:  {'alpha': 2}
Best Score:  0.8366117130238188

In [ ]:
print("Lasso without Poly Features:")
print("Best_params: ", cv.best_params_)
print("Best Score: ", cv.best_score_)

Lasso with Poly Features:
Best_params:  {'alpha': 2}
Best Score:  0.7440345303084998

- The above without poly features is the score where I changed the X_poly to X data and calculating the score.

#### ```Ridge regression with KFold on Polynomial Features```

In [59]:
from sklearn.linear_model import Ridge

In [60]:
#Defining our parameters.
parameters = dict(alpha=[0, 0.001, 0.1, 0.5, 0.8, 1, 1.5, 2])

In [61]:
#Creating an object for Ridge algorithm.
clf = Ridge()

In [62]:
#We are defining our KFold parameters to split data.
kfold = KFold(n_splits= 5, shuffle=True, random_state=2022)

In [63]:
#Creating an object for GridSearchCV with Lasso, parameters that defined above, with folds in cv. Scoring based on R2.
cv = GridSearchCV(estimator=clf, param_grid=parameters, scoring='r2', cv=kfold)

In [64]:
#Split with polynomial feature training data.
cv.fit(X_poly, y)

GridSearchCV(cv=KFold(n_splits=5, random_state=2022, shuffle=True),
             estimator=Ridge(),
             param_grid={'alpha': [0, 0.001, 0.1, 0.5, 0.8, 1, 1.5, 2]},
             scoring='r2')

In [65]:
#we are storing into Dataframe.
df_cv = pd.DataFrame(cv.cv_results_)

In [66]:
df_cv

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.010856,0.008570,0.000963,0.000296,0.000,{'alpha': 0},0.763303,0.827109,0.673251,0.707125,0.848848,0.763927,0.067309,8
1,0.001807,0.001359,0.000401,0.000158,0.001,{'alpha': 0.001},0.877321,0.827779,0.765382,0.861127,0.848344,0.835991,0.038848,7
2,0.000754,0.000029,0.000343,0.000049,0.100,{'alpha': 0.1},0.877381,0.827796,0.765408,0.861099,0.848416,0.836020,0.038851,6
3,0.000752,0.000063,0.000295,0.000007,0.500,{'alpha': 0.5},0.877576,0.827833,0.765490,0.860959,0.848657,0.836103,0.038859,4
4,0.000758,0.000065,0.000320,0.000026,0.800,{'alpha': 0.8},0.877678,0.827834,0.765527,0.860832,0.848795,0.836133,0.038860,2
5,0.000765,0.000093,0.000394,0.000187,1.000,{'alpha': 1},0.877728,0.827824,0.765543,0.860738,0.848869,0.836140,0.038858,1
6,0.000742,0.000030,0.000301,0.000008,1.500,{'alpha': 1.5},0.877803,0.827771,0.765557,0.860479,0.849005,0.836123,0.038848,3
7,0.000767,0.000026,0.000318,0.000015,2.000,{'alpha': 2},0.877820,0.827685,0.765541,0.860195,0.849081,0.836064,0.038831,5

In [67]:
print("Ridge with Poly Features:")
print("Best_params: ", cv.best_params_)
print("Best Score: ", cv.best_score_)

Ridge with Poly Features:
Best_params:  {'alpha': 1}
Best Score:  0.8361404589330894

#### ```ElasticNet regression with KFold on Polynomial Features```

In [68]:
from sklearn.linear_model import ElasticNet

In [77]:
#Defining our parameters.
parameters = dict(
    alpha=[0, 0.001, 0.1, 0.5, 0.8, 1, 1.5, 2], 
    l1_ratio = [0.001, 0.5, 0.7, 1]
)

In [78]:
#Creating an object for Ridge algorithm.
clf = ElasticNet()

In [79]:
#We are defining our KFold parameters to split data.
kfold = KFold(n_splits= 5, shuffle=True, random_state=2026)

In [80]:
#Creating an object for GridSearchCV with Lasso, parameters that defined above, with folds in cv. Scoring based on R2.
cv = GridSearchCV(estimator=clf, param_grid=parameters, scoring='r2', cv=kfold)

In [81]:
#Split with polynomial feature training data.
cv.fit(X_poly, y)

c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.210e+10, tolerance: 1.538e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.177e+10, tolerance: 1.595e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.219e+10, tolerance: 1.611e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.054e+10, tolerance: 1.506e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.268e+10, tolerance: 1.590e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.210e+10, tolerance: 1.538e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.177e+10, tolerance: 1.595e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.219e+10, tolerance: 1.611e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.054e+10, tolerance: 1.506e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.268e+10, tolerance: 1.590e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.210e+10, tolerance: 1.538e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.177e+10, tolerance: 1.595e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.219e+10, tolerance: 1.611e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.054e+10, tolerance: 1.506e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.268e+10, tolerance: 1.590e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.210e+10, tolerance: 1.538e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.177e+10, tolerance: 1.595e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.219e+10, tolerance: 1.611e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(cv=KFold(n_splits=5, random_state=2026, shuffle=True),
             estimator=ElasticNet(),
             param_grid={'alpha': [0, 0.001, 0.1, 0.5, 0.8, 1, 1.5, 2],
                         'l1_ratio': [0.001, 0.5, 0.7, 1]},
             scoring='r2')

In [82]:
#we are storing into Dataframe.
df_cv = pd.DataFrame(cv.cv_results_)

In [83]:
df_cv

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_l1_ratio,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.017486,0.001221,0.000798,0.000190,0.000,0.001,"{'alpha': 0, 'l1_ratio': 0.001}",0.861340,0.820735,0.836905,0.795083,0.874589,0.837730,0.028370,11
1,0.014618,0.000085,0.000504,0.000052,0.000,0.500,"{'alpha': 0, 'l1_ratio': 0.5}",0.861340,0.820735,0.836905,0.795083,0.874589,0.837730,0.028370,11
2,0.015125,0.001841,0.000780,0.000287,0.000,0.700,"{'alpha': 0, 'l1_ratio': 0.7}",0.861340,0.820735,0.836905,0.795083,0.874589,0.837730,0.028370,11
3,0.014417,0.001051,0.000447,0.000089,0.000,1.000,"{'alpha': 0, 'l1_ratio': 1}",0.861340,0.820735,0.836905,0.795083,0.874589,0.837730,0.028370,11
4,0.013024,0.000938,0.000532,0.000036,0.001,0.001,"{'alpha': 0.001, 'l1_ratio': 0.001}",0.861365,0.821753,0.837536,0.795210,0.874009,0.837975,0.028063,3
5,0.011494,0.002313,0.000516,0.000096,0.001,0.500,"{'alpha': 0.001, 'l1_ratio': 0.5}",0.861391,0.821320,0.837290,0.795180,0.874312,0.837899,0.028206,5
6,0.010329,0.001424,0.000551,0.000075,0.001,0.700,"{'alpha': 0.001, 'l1_ratio': 0.7}",0.861374,0.821074,0.837174,0.795139,0.874440,0.837840,0.028278,8
7,0.014532,0.000889,0.000564,0.000022,0.001,1.000,"{'alpha': 0.001, 'l1_ratio': 1}",0.861340,0.820735,0.836906,0.795083,0.874589,0.837730,0.028370,10
8,0.014649,0.000964,0.000543,0.000038,0.100,0.001,"{'alpha': 0.1, 'l1_ratio': 0.001}",0.850875,0.815523,0.829647,0.786912,0.858630,0.828317,0.025720,17
9,0.013267,0.000968,0.000479,0.000062,0.100,0.500,"{'alpha': 0.1, 'l1_ratio': 0.5}",0.852542,0.817283,0.831233,0.788240,0.861071,0.830074,0.026003,16
10,0.013703,0.000433,0.000588,0.000067,0.100,0.700,"{'alpha': 0.1, 'l1_ratio': 0.7}",0.854229,0.818795,0.832787,0.789596,0.863351,0.831752,0.026267,15
11,0.015705,0.000999,0.000618,0.000125,0.100,1.000,"{'alpha': 0.1, 'l1_ratio': 1}",0.861363,0.820753,0.836944,0.795113,0.874586,0.837752,0.028362,9
12,0.010719,0.000888,0.000537,0.000030,0.500,0.001,"{'alpha': 0.5, 'l1_ratio': 0.001}",0.848638,0.812485,0.827837,0.785488,0.854958,0.825881,0.025212,24
13,0.011427,0.002317,0.000732,0.000187,0.500,0.500,"{'alpha': 0.5, 'l1_ratio': 0.5}",0.849527,0.813665,0.828419,0.785910,0.856322,0.826769,0.025437,20
14,0.012229,0.002333,0.000679,0.000097,0.500,0.700,"{'alpha': 0.5, 'l1_ratio': 0.7}",0.850191,0.814636,0.829001,0.786386,0.857496,0.827542,0.025584,18
15,0.011001,0.001137,0.000576,0.000093,0.500,1.000,"{'alpha': 0.5, 'l1_ratio': 1}",0.861518,0.820817,0.837090,0.795197,0.874626,0.837850,0.028364,7
16,0.010857,0.000215,0.000535,0.000024,0.800,0.001,"{'alpha': 0.8, 'l1_ratio': 0.001}",0.847821,0.811758,0.827454,0.785276,0.854109,0.825284,0.025008,28
17,0.009552,0.000176,0.000729,0.000039,0.800,0.500,"{'alpha': 0.8, 'l1_ratio': 0.5}",0.848942,0.812841,0.828009,0.785605,0.855368,0.826153,0.025289,22
18,0.010672,0.000469,0.000789,0.000076,0.800,0.700,"{'alpha': 0.8, 'l1_ratio': 0.7}",0.849571,0.813732,0.828456,0.785945,0.856398,0.826820,0.025445,19
19,0.010866,0.000865,0.000565,0.000103,0.800,1.000,"{'alpha': 0.8, 'l1_ratio': 1}",0.861571,0.820731,0.837199,0.795233,0.874652,0.837877,0.028379,6
20,0.009740,0.000593,0.000816,0.000178,1.000,0.001,"{'alpha': 1, 'l1_ratio': 0.001}",0.847318,0.811435,0.827247,0.785166,0.853714,0.824976,0.024893,29
21,0.008336,0.000550,0.000648,0.000106,1.000,0.500,"{'alpha': 1, 'l1_ratio': 0.5}",0.848629,0.812472,0.827831,0.785490,0.854945,0.825873,0.025208,25
22,0.009061,0.000699,0.000633,0.000103,1.000,0.700,"{'alpha': 1, 'l1_ratio': 0.7}",0.849298,0.813328,0.828247,0.785783,0.855927,0.826517,0.025378,21
23,0.010405,0.001029,0.000769,0.000088,1.000,1.000,"{'alpha': 1, 'l1_ratio': 1}",0.861612,0.820728,0.837270,0.795255,0.874671,0.837907,0.028384,4
24,0.009279,0.000744,0.000575,0.000094,1.500,0.001,"{'alpha': 1.5, 'l1_ratio': 0.001}",0.846119,0.810858,0.826766,0.784869,0.852955,0.824313,0.024653,31
25,0.007845,0.000553,0.000795,0.000033,1.500,0.500,"{'alpha': 1.5, 'l1_ratio': 0.5}",0.847937,0.811838,0.827501,0.785307,0.854208,0.825358,0.025034,27
26,0.008390,0.000567,0.000819,0.000104,1.500,0.700,"{'alpha': 1.5, 'l1_ratio': 0.7}",0.848771,0.812631,0.827909,0.785546,0.855128,0.825997,0.025242,23
27,0.010749,0.000785,0.000775,0.000186,1.500,1.000,"{'alpha': 1.5, 'l1_ratio': 1}",0.861710,0.820753,0.837445,0.795307,0.874714,0.837986,0.028392,2
28,0.009626,0.000371,0.000852,0.000093,2.000,0.001,"{'alpha': 2, 'l1_ratio': 0.001}",0.844956,0.810416,0.826272,0.784483,0.852314,0.823688,0.024461,32
29,0.008072,0.000568,0.000765,0.000278,2.000,0.500,"{'alpha': 2, 'l1_ratio': 0.5}",0.847304,0.811415,0.827237,0.785169,0.853696,0.824964,0.024888,30
30,0.008968,0.000321,0.000712,0.000112,2.000,0.700,"{'alpha': 2, 'l1_ratio': 0.7}",0.848329,0.812164,0.827678,0.785410,0.854592,0.825635,0.025129,26
31,0.011206,0.000904,0.000795,0.000187,2.000,1.000,"{'alpha': 2, 'l1_ratio': 1}",0.861931,0.820909,0.837580,0.795428,0.874517,0.838073,0.028322,1

In [84]:
print("ElasticNet with Poly Features:")
print("Best_params: ", cv.best_params_)
print("Best Score: ", cv.best_score_)

ElasticNet with Poly Features:
Best_params:  {'alpha': 2, 'l1_ratio': 1}
Best Score:  0.8380728638729756