In [1]:
# Q1. Count Character frequency?

text = 'hello'
freq = {}

for char in text:
    if char in freq:
        freq[char] += 1
    else:
        freq[char] = 1

print(freq)

{'h': 1, 'e': 1, 'l': 2, 'o': 1}

In [2]:
from collections import Counter
freq = Counter(char)
print(freq)

Counter({'o': 1})

In [3]:
# Q2. Find Duplicates elements?

In [4]:
help('def')

Function definitions
********************

A function definition defines a user-defined function object (see
section The standard type hierarchy):

   funcdef                   ::= [decorators] "def" funcname [type_params] "(" [parameter_list] ")"
                                 ["->" expression] ":" suite
   decorators                ::= decorator+
   decorator                 ::= "@" assignment_expression NEWLINE
   parameter_list            ::= defparameter ("," defparameter)* "," "/" ["," [parameter_list_no_posonly]]
                                 | parameter_list_no_posonly
   parameter_list_no_posonly ::= defparameter ("," defparameter)* ["," [parameter_list_starargs]]
                                 | parameter_list_starargs
   parameter_list_starargs   ::= "*" [star_parameter] ("," defparameter)* ["," [parameter_star_kwargs]]
                                 | "*" ("," defparameter)+ ["," [parameter_star_kwargs]]
                                 | parameter_star_kwargs
   parameter_star_kwargs     ::= "**" parameter [","]
   parameter                 ::= identifier [":" expression]
   star_parameter            ::= identifier [":" ["*"] expression]
   defparameter              ::= parameter ["=" expression]
   funcname                  ::= identifier

A function definition is an executable statement.  Its execution binds
the function name in the current local namespace to a function object
(a wrapper around the executable code for the function).  This
function object contains a reference to the current global namespace
as the global namespace to be used when the function is called.

The function definition does not execute the function body; this gets
executed only when the function is called. [4]

A function definition may be wrapped by one or more *decorator*
expressions. Decorator expressions are evaluated when the function is
defined, in the scope that contains the function definition.  The
result must be a callable, which is invoked with the function object
as the only argument. The returned value is bound to the function name
instead of the function object.  Multiple decorators are applied in
nested fashion. For example, the following code

   @f1(arg)
   @f2
   def func(): pass

is roughly equivalent to

   def func(): pass
   func = f1(arg)(f2(func))

except that the original function is not temporarily bound to the name
"func".

Changed in version 3.9: Functions may be decorated with any valid
"assignment_expression". Previously, the grammar was much more
restrictive; see **PEP 614** for details.

A list of type parameters may be given in square brackets between the
function’s name and the opening parenthesis for its parameter list.
This indicates to static type checkers that the function is generic.
At runtime, the type parameters can be retrieved from the function’s
"__type_params__" attribute. See Generic functions for more.

Changed in version 3.12: Type parameter lists are new in Python 3.12.

When one or more *parameters* have the form *parameter* "="
*expression*, the function is said to have “default parameter values.”
For a parameter with a default value, the corresponding *argument* may
be omitted from a call, in which case the parameter’s default value is
substituted.  If a parameter has a default value, all following
parameters up until the “"*"” must also have a default value — this is
a syntactic restriction that is not expressed by the grammar.

**Default parameter values are evaluated from left to right when the
function definition is executed.** This means that the expression is
evaluated once, when the function is defined, and that the same “pre-
computed” value is used for each call.  This is especially important
to understand when a default parameter value is a mutable object, such
as a list or a dictionary: if the function modifies the object (e.g.
by appending an item to a list), the default parameter value is in
effect modified.  This is generally not what was intended.  A way
around this is to use "None" as the default, and explicitly test for
it in the body of the function, e.g.:

   def whats_on_the_telly(penguin=None):
       if penguin is None:
           penguin = []
       penguin.append("property of the zoo")
       return penguin

Function call semantics are described in more detail in section Calls.
A function call always assigns values to all parameters mentioned in
the parameter list, either from positional arguments, from keyword
arguments, or from default values.  If the form “"*identifier"” is
present, it is initialized to a tuple receiving any excess positional
parameters, defaulting to the empty tuple. If the form
“"**identifier"” is present, it is initialized to a new ordered
mapping receiving any excess keyword arguments, defaulting to a new
empty mapping of the same type.  Parameters after “"*"” or
“"*identifier"” are keyword-only parameters and may only be passed by
keyword arguments.  Parameters before “"/"” are positional-only
parameters and may only be passed by positional arguments.

Changed in version 3.8: The "/" function parameter syntax may be used
to indicate positional-only parameters. See **PEP 570** for details.

Parameters may have an *annotation* of the form “": expression"”
following the parameter name.  Any parameter may have an annotation,
even those of the form "*identifier" or "**identifier". (As a special
case, parameters of the form "*identifier" may have an annotation “":
*expression"”.) Functions may have “return” annotation of the form
“"-> expression"” after the parameter list.  These annotations can be
any valid Python expression.  The presence of annotations does not
change the semantics of a function.  The annotation values are
available as values of a dictionary keyed by the parameters’ names in
the "__annotations__" attribute of the function object.  If the
"annotations" import from "__future__" is used, annotations are
preserved as strings at runtime which enables postponed evaluation.
Otherwise, they are evaluated when the function definition is
executed.  In this case annotations may be evaluated in a different
order than they appear in the source code.

Changed in version 3.11: Parameters of the form “"*identifier"” may
have an annotation “": *expression"”. See **PEP 646**.

It is also possible to create anonymous functions (functions not bound
to a name), for immediate use in expressions.  This uses lambda
expressions, described in section Lambdas.  Note that the lambda
expression is merely a shorthand for a simplified function definition;
a function defined in a “"def"” statement can be passed around or
assigned to another name just like a function defined by a lambda
expression.  The “"def"” form is actually more powerful since it
allows the execution of multiple statements and annotations.

**Programmer’s note:** Functions are first-class objects.  A “"def"”
statement executed inside a function definition defines a local
function that can be returned or passed around.  Free variables used
in the nested function can access the local variables of the function
containing the def.  See section Naming and binding for details.

See also:

  **PEP 3107** - Function Annotations
     The original specification for function annotations.

  **PEP 484** - Type Hints
     Definition of a standard meaning for annotations: type hints.

  **PEP 526** - Syntax for Variable Annotations
     Ability to type hint variable declarations, including class
     variables and instance variables.

  **PEP 563** - Postponed Evaluation of Annotations
     Support for forward references within annotations by preserving
     annotations in a string form at runtime instead of eager
     evaluation.

  **PEP 318** - Decorators for Functions and Methods
     Function and method decorators were introduced. Class decorators
     were introduced in **PEP 3129**.

In [5]:
print("Hello My name is %s and I'm now in %s for a trip."%('Rakshith','Banglore'))
print('What is series count: %d' %(45))
print('My name is {} and I live in {}, with number of points {}'.format('Rakshith','Banglore',67))
print(f'my name is {'Rakshith'}')

Hello My name is Rakshith and I'm now in Banglore for a trip.
What is series count: 45
My name is Rakshith and I live in Banglore, with number of points 67
my name is Rakshith

In [6]:
import pandas as pd

In [7]:
my_data = [10,20,30]
labels = ['A','B','C']

In [8]:
pd.Series(data=my_data, index=labels)

A    10
B    20
C    30
dtype: int64

In [9]:
ser1 = pd.Series([1,2,3,4],['US','IND','AUS','WI'])
ser2 = pd.Series([1,2,3,4],['US','IND','ENG','WI'])

In [10]:
ser1 + ser2

AUS    NaN
ENG    NaN
IND    4.0
US     2.0
WI     8.0
dtype: float64

In [11]:
import numpy as np
from numpy.random import randn
np.random.seed()

In [12]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

          W         X         Y         Z
A  0.162680  0.365676  0.996196 -1.244814
B -1.113557  1.527922 -0.802025  0.070558
C  0.688178 -0.738624 -0.503347  1.191210
D -0.703257 -0.994767  0.276055  1.980011
E  1.852561  1.732890 -0.188281 -1.721437

In [13]:
df[['W','Y']]

          W         Y
A  0.162680  0.996196
B -1.113557 -0.802025
C  0.688178 -0.503347
D -0.703257  0.276055
E  1.852561 -0.188281

In [14]:
df['new'] = df['X'] + df['Z']

In [15]:
df

          W         X         Y         Z       new
A  0.162680  0.365676  0.996196 -1.244814 -0.879138
B -1.113557  1.527922 -0.802025  0.070558  1.598479
C  0.688178 -0.738624 -0.503347  1.191210  0.452587
D -0.703257 -0.994767  0.276055  1.980011  0.985244
E  1.852561  1.732890 -0.188281 -1.721437  0.011454

In [16]:
df.drop('E',axis=0)

          W         X         Y         Z       new
A  0.162680  0.365676  0.996196 -1.244814 -0.879138
B -1.113557  1.527922 -0.802025  0.070558  1.598479
C  0.688178 -0.738624 -0.503347  1.191210  0.452587
D -0.703257 -0.994767  0.276055  1.980011  0.985244

In [17]:
df.iloc[2,2]

np.float64(-0.5033469025853371)

In [18]:
df[df > 0]

          W         X         Y         Z       new
A  0.162680  0.365676  0.996196       NaN       NaN
B       NaN  1.527922       NaN  0.070558  1.598479
C  0.688178       NaN       NaN  1.191210  0.452587
D       NaN       NaN  0.276055  1.980011  0.985244
E  1.852561  1.732890       NaN       NaN  0.011454

In [19]:
df[df['X']>0][['W','new']]

          W       new
A  0.162680 -0.879138
B -1.113557  1.598479
E  1.852561  0.011454

In [20]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [21]:
df = pd.DataFrame(randn(6,2),hier_index,['A','B'])
df

             A         B
G1 1 -1.009469 -0.621409
   2 -0.822255 -1.002849
   3  1.137427 -0.679317
G2 1  0.552128  0.856759
   2  0.489895  1.198668
   3 -0.140025  0.989571

In [22]:
df.loc['G1'].loc[1].loc['B']

np.float64(-0.6214087351291949)

In [23]:
df.loc['G2'].loc[1].loc['B']

np.float64(0.8567590207350483)

In [24]:
d = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}
df = pd.DataFrame(d)
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [25]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [26]:
df.fillna(df['A'].mean())

     A    B  C
0  1.0  5.0  1
1  2.0  1.5  2
2  1.5  1.5  3

In [27]:
data = {
    'company': ['goog','goog','msft','msft','fb','fb'],
    'person': ['sam','charlie','amy','vaneesa','carl','sarah'],
    'sales': [200,120,340,124,243,350]
}

In [28]:
df = pd.DataFrame(data)
df

  company   person  sales
0    goog      sam    200
1    goog  charlie    120
2    msft      amy    340
3    msft  vaneesa    124
4      fb     carl    243
5      fb    sarah    350

In [29]:
df.groupby('company')['sales'].sum()

company
fb      593
goog    320
msft    464
Name: sales, dtype: int64

In [30]:
df.groupby('company')['sales'].agg(['mean','std'])

          mean         std
company
fb       296.5   75.660426
goog     160.0   56.568542
msft     232.0  152.735065

In [31]:
df.groupby('company').describe().transpose()

company              fb        goog        msft
sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [32]:
df1 = pd.DataFrame({
    'A':['A0','A1','A2','A3'],
    'B':['B0','B1','B2','B3'],
    'C':['C0','C1','C2','C3'],
    'D':['D0','D1','D2','D3']}, 
    index=[0,1,2,3]
)

df2 = pd.DataFrame({
    'A':['A4','A5','A6','A7'],
    'B':['B4','B5','B6','B7'],
    'C':['C4','C5','C6','C7'],
    'D':['D4','D5','D6','D7']}, 
    index=[4,5,6,7]
)

df3 = pd.DataFrame({
    'A':['A8','A9','A10','A11'],
    'B':['B8','B9','B10','B11'],
    'C':['C8','C9','C10','C11'],
    'D':['D8','D9','D10','D11']},
     index=[8,9,10,11]
)

In [63]:
pd.concat([df1,df2,df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [76]:
left = pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2']},
    index= ['K0','K1','K2'])

right = pd.DataFrame({
    'C':['C0','C1','C2'],
    'D':['D0','D1','D2']},
    index= ['K0','K2','K3'])

In [68]:
pd.merge(left,right,on='key',how='inner')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [71]:
pd.merge(left,right, on='key',how='outer')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [77]:
left.join(right)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C1   D1

In [78]:
df = pd.DataFrame({
    'col1':[1,2,3,4],
    'col2':[444,555,666,444],
    'col3':['abc','def','ghi','xyz']
})

df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [81]:
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [83]:
df[(df['col1'] > 2) & (df['col2'] == 444)]

   col1  col2 col3
3     4   444  xyz

In [84]:
def times(x):
    return x * x

In [86]:
df['col1'].apply(lambda x:x*2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [88]:
df.drop('col3', axis=1)

   col1  col2
0     1   444
1     2   555
2     3   666
3     4   444

In [89]:
df.sort_values(by='col2')

   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [94]:
data = {
    'A':['foo','foo','foo','bar','bar','bar'],
    'B':['one','one','two','two','one','one'],
    'C':['x','y','x','y','x','y'],
    'D':[1,3,2,5,4,1]
}

df = pd.DataFrame(data)
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [95]:
df.pivot_table(values='D', index=['A','B'], columns='C')

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

```Dictonary```

In [33]:
dict = {
    1:'Hello',
    2:'Bye',
    3:'Good'
}

dict

{1: 'Hello', 2: 'Bye', 3: 'Good'}

In [34]:
len(dict)

3

In [35]:
print(dict.get(4))

None

In [36]:
#Adding an item
dict[4] = 'Love'
dict

{1: 'Hello', 2: 'Bye', 3: 'Good', 4: 'Love'}

In [37]:
#Modifying existing element
dict[4] = 'Mobile'
dict

{1: 'Hello', 2: 'Bye', 3: 'Good', 4: 'Mobile'}

In [38]:
print(2 in dict) #True
print(6 in dict) #False

True
False

In [39]:
del dict

In [40]:
dict

dict

In [41]:
dct = {
    'key1':'value1',
    'key2':'value2',
    'key3':'value3',
    'key4':'value4',
    'key5':'value5'
}
dct

{'key1': 'value1',
 'key2': 'value2',
 'key3': 'value3',
 'key4': 'value4',
 'key5': 'value5'}

In [42]:
dct.items()

dict_items([('key1', 'value1'), ('key2', 'value2'), ('key3', 'value3'), ('key4', 'value4'), ('key5', 'value5')])

In [43]:
dct_copy = dct.copy()
dct_copy

{'key1': 'value1',
 'key2': 'value2',
 'key3': 'value3',
 'key4': 'value4',
 'key5': 'value5'}

```Conditions```

In [44]:
#IF
age = 20
if age == 20:
    print('Execute this block.')

Execute this block.

In [45]:
#IF-ELSE
if age > 20:
    print("Execute IF Block")
else:
    print("Execute Else Block")

Execute Else Block

In [46]:
#IF-ELIF-ELSE

if age > 20:
    print('This is IF block')
elif age > 18 and age <= 20:
    print("This is ELIF block")
else:
    print('This is ELSE block')

This is ELIF block

In [47]:
height = 120
if age >= 20:
    print("You can enter contest but we need your height to move further")
    if height >= 120:
        print("Enjoy the contest")
    else:
        print("You can't enter the contest")
else:
    print("You are under age to join the contest.")

You can enter contest but we need your height to move further
Enjoy the contest

In [48]:
count = 0

while count < 5:
    print('Block ended')
    count += 1
else:
    print("Else Block")

Block ended
Block ended
Block ended
Block ended
Block ended
Else Block

In [49]:
count = 0

while count < 5:
    print(count)
    count += 1
    if count == 4:
        break
print('Loop got break')

0
1
2
3
Loop got break

In [50]:
count = 0

while count < 5:
    if count == 3:
        count += 1
        continue
    print(count)
    count += 1

0
1
2
4

In [51]:
lst = [1,2,3,4,5,6]

for i in lst:
    print(i)

1
2
3
4
5
6

In [52]:
st = 'HELLO'

for i in st:
    print(i)

H
E
L
L
O

In [53]:
dct = {
    'key1':'value1',
    'key2':'value2',
    'key3':'value3',
    'key4':'value4',
    'key5':'value5'
}

for i in dct:
    print(i)

key1
key2
key3
key4
key5

In [54]:
for key, value in dct.items():
    print(key, value)

key1 value1
key2 value2
key3 value3
key4 value4
key5 value5

In [55]:
for i in lst:
    print(i)
    if i == 3:
        break

1
2
3

In [56]:
for i in lst:
    if i == 3:
        continue
    print(i)

1
2
4
5
6

In [57]:
for i in range(6):
    if i > 4:
        break
    print(i)

0
1
2
3
4

In [58]:
for i in lst:
    for j in range(3):
        print(j)

0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2

In [59]:
for i in range(4):
    print(i)
else:
    print("Loop ended.")

0
1
2
3
Loop ended.

In [60]:
for i in range(8):
    print('#'*i)

#
##
###
####
#####
######
#######

In [61]:
for i in range(8):
    for j in range(7):
        print(end="# ")
    print('# ')

# # # # # # # #
# # # # # # # #
# # # # # # # #
# # # # # # # #
# # # # # # # #
# # # # # # # #
# # # # # # # #
# # # # # # # #

In [62]:
my_dct = {'name':'Rakshith', 'location': 'Bangalore'}

def greet(name, location):
    msg = 'Hello ' + name + " You're in " + location
    return msg

print(greet(**my_dct))

Hello Rakshith You're in Bangalore