$$ DataFrames $$

DataFrame: These are two-dimensional and labeled datastructures of different datatypes. It provides efficient data manipulation, data cleaning, aggregations, and Analysis.

- It is similar to excel spreadsheet
- It integrates with other libraries like Numpy, Matplotlib for core building block for Visualization, Aggregations and working with data.
- It handles data from execl (read_excel), CSV (read_csv) format and SQL Databases.

In [2]:
import numpy as np
import pandas as pd
from numpy.random import randn

seed() - A seed is the initial value used by a pseudo random number generator. Using the same seed produces the same sequence of random numbers everytime.

42 is used for most conventional among programmers. Any integer can be given.

In [3]:
np.random.seed(101)

In [4]:
#We are creating a dataframe from the above random values using headers and indexes.
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

##### ```Indexing```

In [5]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [6]:
#The column is a series datatype.
type(df['W'])

pandas.Series

In [7]:
#The df is of type DataFrame but the columns can be series.
type(df)

pandas.DataFrame

In [8]:
#we can use dot notation but it will be confusing in complex querying
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [9]:
#If you need to query multiple columns use list passing inside dataframe. We are passing two columns ['W','X'] in list format.

df[['W','X']]

          W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

##### Creating New column

In [10]:
# df['New_Column']

#This will give a key error as complier thinks there is no column with the name mentioned.

In [11]:
#We need use like exisiting and need to use equal to assignment to produce a new column like below example.

df['New_Column'] = df['W'] + df['Y']
df

          W         X         Y         Z  New_Column
A  2.706850  0.628133  0.907969  0.503826    3.614819
B  0.651118 -0.319318 -0.848077  0.605965   -0.196959
C -2.018168  0.740122  0.528813 -0.589001   -1.489355
D  0.188695 -0.758872 -0.933237  0.955057   -0.744542
E  0.190794  1.978757  2.605967  0.683509    2.796762

```py
To dropping a Column we can use the drop()

Syntax:
dataframe.drop("Column Name",axis=1)

Axis = 0 if you are dropping an row item.
Axis = 1 if you are dropping an column item
```

In [12]:

# To drop New_column
#df.drop('New')  #This will produce a value error as we haven't provided the axis by default it search through row wise so in rows it can't find what we want to drop so we need to use axis=1 to look by column wise.

In [13]:
#Droping 'New_Column'
df.drop('New_Column',axis=1)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

```py

- In the above code we have dropped the column: 'New_Column' but later below if we check on the df the column is still available, this is because we have been working in a view of the original dataframe. To apply the changes on the orginal dataframe we need to use inplace=True.

- By default the inplace = False accidentally not lose the data during manipulation.
```

In [14]:
df.head(2)

          W         X         Y         Z  New_Column
A  2.706850  0.628133  0.907969  0.503826    3.614819
B  0.651118 -0.319318 -0.848077  0.605965   -0.196959

In [15]:
#We are using inplace=True in dropping the Column: 'New_Column'
df.drop('New_Column', axis=1, inplace=True)

In [16]:
#To find the shape of the dataframe
df.shape

#5 rows, 4 Columns. Due to this we have concept of axis of 0 & 1.

(5, 4)

##### ```Selection```

```py
.loc[] is a label-based indexer in pandas. It is used to select the rows/columns by their labels (names) not by position.

Syntax:
- df.loc[row_label,col_label]


#Selecting single row
df.loc['Column_name']

#Selecting multiple rows using list passing.
df.loc[['Col1','Col2']]

#To fetch specific row and column
df.loc['row','col']

#Selecting multiple columns
df.loc[:,['Column_name']]

#Selecting with conditions
df.loc[df['age'] > 25]

#Filtering and selecting specific column
df.loc[df['age] > 25,['Column_name']]

#Update the value
df.loc['A','age'] = 40


#Slicing with labels
df.loc['A':'B']
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```py
.iloc[] stands for Integer location and is used to select rows and columns based on their position numbers (Index Positions)

Syntax:
df.iloc[row_position, column_position]


#1. Selecting a single row
df.iloc[1]

#2. Selecting Multiple rows passing with list items.
df.iloc[[0,2]]

#3. Selecting single value
df.iloc[1,1]

#4. Selecting specific rows and columns
df.iloc[[0,2],[0,1]]

#5. Slicing Rows
df.iloc[0:2]

#6. Slicing rows and columns
df.iloc[[0:2],[0:2]]

#7. All rows and specific columns
df.iloc[:,[0:2]]

#8. Last row
df.iloc[-1]

```

```
loc = Location by label (row/column names)
iloc = integer location (row/column position)
```

In [17]:
#Rows label based
df.loc['C']

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [18]:
#Same above using iloc. We can see that C is in 2 position.
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [19]:
#Subset
df.loc['B','Y']

np.float64(-0.8480769834036315)

In [20]:
#subset of A,B and W,Y
df.loc[['A','B'],['W','Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

#### ```Conditional Selection```

In [21]:
#If we use conditional on dataframe it will return boolean type dataframe, where a value meet the condition be True and not met value will be False.
df > 0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [22]:
#we are assigning the bool value to new dataframe to get the actual condition.

booldf = df > 0
booldf

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [23]:
#If we take our original dataframe and give this conditional dataframe it will return the result with values and not met condition values with NAN.
df[booldf]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [24]:
#We are using a column of the dataframe to validate with our condition. It will return a series of boolean expressions for the values of data.
df['W'] > 0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [25]:
#When look into a dataframe with specific condition on the column it only return which met with condition rest are skipped.
df[df['W'] > 0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [26]:
#Fetch rows whose value is less than zero.
df[df['Z'] < 0]

          W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [27]:
#Fetch the data where column Z is greater than 0 and only need X,Y columns.
df[df['W']>0][['X','Y']]

          X         Y
A  0.628133  0.907969
B -0.319318 -0.848077
D -0.758872 -0.933237
E  1.978757  2.605967

- To check with multiple conditions in Pandas. 
- Use parenthesis for each condition and if you are using "AND" then replace with "&". 
- As "AND" take single condition so it will be ambigious in series conditions.

    - AND for & 
    - OR for |

In [28]:
#Multiply condition.
df[(df['W'] > 0) & (df['X'] > 0)]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
E  0.190794  1.978757  2.605967  0.683509

```py
reset_index() is a pandas function used to reset the Dataframe index back to the default intgere index (0,1,2,3,..)

- It is commonly used after filtering, sorting, grouping, or deleting rows when the index become irregular.

Syntax:
reset_index()


- If we use drop=True inside the function it will drop the previous index.
reset_index(drop=True)
```

In [29]:
# restoring default index. 
# This will be a view and directly applies on the original dataframe. Use inplace=True
df.reset_index()

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

- set_index(column_name) - will create a new index of the column name mentioned.

In [30]:
#We will create a new index values and assign it to our dataframe and make it as new index.

new_index = 'CA NY WY OR CO'.split()  #We are splitting each string to seperate in a list format.
# new_index

#we are assigning new list values to original dataframe with column name as 'States'.
df['states'] = new_index

df.set_index('states')

               W         X         Y         Z
states
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

##### ```Multi-Level indexing (Hierachical Indexing)```

```py
Multi-Level Indexing allows a Dataframe to have more than one index level on rows or columns.
```

In [31]:
#Index levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [33]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [34]:
df1 = pd.DataFrame(randn(6,2),hier_index,['A','B'])
df1

             A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [ ]:
#If we need to access any elements in the dataframe. we can call outside index and go step by step inside the dataframe.
df1.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [38]:
#By default there are no names for the index it will be none
df1.index.names

FrozenList([None, None])

In [39]:
#We can assign new index names to the dataframe by passing through the list items
df1.index.names = ['Groups','Numbers']

In [40]:
df1

                       A         B
Groups Numbers
G1     1        0.302665  1.693723
       2       -1.706086 -1.159119
       3       -0.134841  0.390528
G2     1        0.166905  0.184502
       2        0.807706  0.072960
       3        0.638787  0.329646

In [ ]:
#Example in access an element: 0.072960 from a multi level index dataframe.

#df1                            #Dataframe level
#df1.loc['G2']                  #Outer index
#df1.loc['G2'].loc[2]           #inside index
df1.loc['G2'].loc[2].loc['B']   #Item level

# Dataframe level >> outerindex >> inside index >> item level.

np.float64(0.07295967531703869)

- Use cross section (xs) for selecting data from specific level.

Syntax:
df.xs(index value, level=inside index)

In [43]:
#Select the data of Numbers '1'.
df1.xs(1,level='Numbers')

               A         B
Groups
G1      0.302665  1.693723
G2      0.166905  0.184502