$$ DataFrames Part-2 $$
### ```Missing Data```

In [1]:
import numpy as np
import pandas as pd

In [2]:
#Creating a Dictionary with null values.
d = {'A': [1,2,np.nan],
     'B':[5,np.nan,np.nan],
     'C':[1,2,3]
}

#We are converting the dictionary into Dataframe
df = pd.DataFrame(d)

#Display of the dataframe
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

```py
**Missing Values:**
- Missing values indicates that the data is not avilable.
- It can be NaN, None, pd.NA (newer version indicator).


#Detect Missing Values
df.isnull() / isna() - returns True where values are missing.

#Remove missing values
1. drop rows: It will remove the rows having null values
  df.dropna()

2. Drop Columns: Remove columns that contain missing values.
    df.dropna(axis=1)

3. Drop Rows only when all values are missing
    df.dropna(how='all)
```

In [3]:
#dropping null values
df.dropna() # This method helps in removing all null values in the rows. It's a view not implise on original until you use inplace=True.


#By default the axis=0

     A    B  C
0  1.0  5.0  1

In [4]:
#Dropping null values in column wise search using axis=1
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [5]:
df.dropna(how='all') #This won't work as all the rows need to be null to make it work.

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [6]:
#Using Threshold parameter to handle missing values. The rows having threshold of 2 are skipped.
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

```py
**Fill Missing Values**

#fill with constant value
df.fillna(0)


#fill numeric columns with mean
df['age'] = df['age'].fillna(df['age'].mean())

#fill with median
df['age'] = df['age'].fillna(df['age'].median())

#fill with mode
#mostly used with categorical columns.
df['name'] = df['name'].fillna(df['name'].mode()[0])
```

In [7]:
df.fillna(value='fill_value')       #This will fill the value where it finds the missing values.
df['A'].fillna(value=df['A'].mean())      #This will fill with mean of the column.
df['B'].fillna(df['B'].median())    #This will fill the column with median.

0    5.0
1    5.0
2    5.0
Name: B, dtype: float64

Q1. How do you handle missing values?

- First we need to identify the missing values using isnull()
- Analyse the columns and distribution of the data across the columns.
- For numerical use mean, median imputation, and for categorical use mode imputation.
- drop the rows or columns which are having missing values more than 60,80%.
- validate the impact as it should not be bias.

#### ```Groupby```

```py
- GroupBy allows you to group together rows based off of a column or many and perform an aggregate function on them. 
- By itself it will return a groupby object

- Groupby only creates a group and on those group we need to perform opertions like mean(),sum(), max()
- Use a variable when you think that you wuld perform multiple calculations. most used for reusability and readability.

#Single column aggrgation
df.groupby('company')['sales'].sum()

#Multiple Aggregations. will pass aggregation through list items.
df.groupby('Department')['Salary'].agg(['sum','max','mean'])


```

In [8]:
#Creating a dictionary data
data = {'company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
        'person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
        'sales':[200,120,340,124,243,350]
}

#Converting Dictionary to dataframe
df1 = pd.DataFrame(data)

#Display dataframe
df1

  company   person  sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [9]:
#Ex1: Grouping them based on company.
df1.groupby('company') #This will create a groupby object. We need to use aggregate function on the columns.

In [10]:
df1.groupby('company')['sales'].sum()

company
FB      593
GOOG    320
MSFT    464
Name: sales, dtype: int64

In [11]:
#Multiple aggregation example

# mean & Standard deviation of sales based on company
df1.groupby('company')['sales'].agg(['mean','std'])

          mean         std
company
FB       296.5   75.660426
GOOG     160.0   56.568542
MSFT     232.0  152.735065

In [12]:
#based on above condition if we need only Google
df1.groupby('company')['sales'].agg(['mean','std']).loc['GOOG']

mean    160.000000
std      56.568542
Name: GOOG, dtype: float64

In [13]:
#Count
df1.groupby('company').count()

         person  sales
company
FB            2      2
GOOG          2      2
MSFT          2      2

In [14]:
#max on categorical column returns alphabetical order fetching on groupby items.
df1.groupby('company').max()

#If we close look into result we can see that sales are irrespective we only defined based on company.

          person  sales
company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [15]:
#Statistical information on the dataframe using describe method.
df1.groupby('company').describe()

        sales
        count   mean         std    min     25%    50%     75%    max
company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

#### ```Joining, Merging and Concatenation```

In [16]:
df1 = pd.DataFrame({
    'A':['A0','A1','A2','A3'],
    'B':['B0','B1','B2','B3'],
    'C':['C0','C1','C2','C3'],
    'D':['D0','D1','D2','D3']}, 
    index=[0,1,2,3]
)

df2 = pd.DataFrame({
    'A':['A4','A5','A6','A7'],
    'B':['B4','B5','B6','B7'],
    'C':['C4','C5','C6','C7'],
    'D':['D4','D5','D6','D7']}, 
    index=[4,5,6,7]
)

df3 = pd.DataFrame({
    'A':['A8','A9','A10','A11'],
    'B':['B8','B9','B10','B11'],
    'C':['C8','C9','C10','C11'],
    'D':['D8','D9','D10','D11']},
     index=[8,9,10,11]
)

In [17]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [18]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [19]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

##### ```Concatenation:```
- Concatenation glues together dataframes, both the dimensions shoild match along the axis you are concatenating on.
- use pd.concat and pass list of dataframes.

Syntax:
pd.concat([df1,df2,df3])

In [21]:
pd.concat([df1,df2,df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [22]:
#if we use axis parameter and look with column wise then the empty cells will be null values.
pd.concat([df1,df2,df3],axis=1)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [23]:
#Example Dataframe
left = pd.DataFrame({
    'key':['K0','K1','K2','K3'],
    'A':['A0','A1','A2','A3'],
    'B':['B0','B1','B2','B3']})

right = pd.DataFrame({
    'key':['K0','K1','K2','K3'],
    'C':['C0','C1','C2','C3'],
    'D':['D0','D1','D2','D3']})

In [24]:
left

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [25]:
right

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

##### ```Merging```
- The merging function allows you to merge Dataframes together using a similar logic as merging SQL tables together.
- Key acts as a primary key for both tables to join.

In [26]:
pd.merge(left,right, how='inner',on='key')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [32]:
left = pd.DataFrame({
    'key1':['K0','K0','K1','K2'],
    'key2':['K0','K1','K0','K1'],
    'A':['A0','A1','A2','A3'],
    'B':['B0','B1','B2','B3']})

right = pd.DataFrame({
    'key1':['K0','K1','K1','K2'],
    'key2':['K0','K0','K0','K0'],
    'C':['C0','C1','C2','C3'],
    'D':['D0','D1','D2','D3']})

In [33]:
# Merging two columns if you have multiple primary keys.
pd.merge(left,right, on=['key1','key2'])

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [ ]:
# OUter merge
pd.merge(left,right, how='outer',on=['key1','key2'])

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

In [ ]:
#right merging
pd.merge(left,right,how='right',on=['key1','key2'])

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

##### ```Joining```
- Joining is a convinent method for combining the columns of two different indexed dataframes into a single resulted dataframe.

In [37]:
left = pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2']},
    index=['K0','K1','K2'])

right = pd.DataFrame({
    'C':['C0','C1','C2'],
    'D':['D0','D1','D2']},
    index=['K0','K2','K3'])

In [38]:
left.join(right)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C1   D1

In [39]:
#Outer Join
left.join(right, how='outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C1   D1
K3  NaN  NaN   C2   D2

In [40]:
#right join
left.join(right, how='right')

      A    B   C   D
K0   A0   B0  C0  D0
K2   A2   B2  C1  D1
K3  NaN  NaN  C2  D2