#### ```Data Input & Output```

- CSV
- EXCEL
- HTML
- SQL

- To work with above files we need to instal few libraries:

1. pip innstall sqlalchemy
2. pip install lxml
3. pip install html5lib
4. pip install BeautifulSoup4

In [32]:
#Import necessary libraries
import pandas as pd

#### ```Reading the CSV file into DataFrame.```
- We need to provide the exact location of the data from Target source or else if you are working in current directory you can directly give the file_name.csv

In [33]:
pd.read_csv(r"C:\Users\raksh\Downloads\DATA SCIENCE\Python for DataScience\Datafiles\Titanic.csv").head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [34]:
#here we are assigning to variable df our dataset.
df = pd.read_csv(r"C:\Users\raksh\Downloads\DATA SCIENCE\Python for DataScience\Datafiles\Titanic.csv").head()

```py
- to_* methods for exporting /serializing the dataframes to different formats.


Syntax:
cleaned_df.to_csv('New_dataframe.csv', index=False)

df.to_csv("output.csv")        # → CSV file
df.to_excel("output.xlsx")     # → Excel file
df.to_json("output.json")      # → JSON file
df.to_dict("records")          # → [{"Name": "Alice", "Age": 25}, ...]
df.to_numpy()                  # → numpy array

```

In [35]:
#For example we are converting the file to csv, where it assign new index and older index is named as unnamed.
df.to_csv('my_output')

In [36]:
pd.read_csv('my_output').head(2)

#as we can see that unnamed column is created on older index for this reason we need to use index=False while writing to new data format.

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [37]:
#To avoid above issue we use index=False
df.to_csv('my_output',index=False)

In [38]:
#The above issue has been solved by index = False.
pd.read_csv('my_output').head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

```Note:```
- Pandas can read calculations, marcos, operations while reading the files from different formats. It will crash or run for longer hours.

```py
- When we need to read file from excel we need to use read_excel() method.

#install library or setup:
- pip install xlrd
- pip install openpyxl

Syntax:
read_excel(file_name.xlsx, sheet_name='Sheet1',index=False/True)


To write to excel:
- df.to_excel('new_excel.xlxs', sheet_name='Sheet1')

df - old file
new_excel.xlxs - new excel file we are trying to save.
sheet_name - which sheet we are trying to save.
```

In [39]:
df = pd.read_excel(r"C:\Users\raksh\Downloads\example_sample.xlsx",sheet_name='Sheet1')
df

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [40]:
#Writin to excel file
df.to_excel('my_output.xlsx',sheet_name='Sheet1')

In [41]:
#Reading the excel new file.
pd.read_excel('my_output.xlsx', sheet_name='Sheet1')

   Unnamed: 0.1  Unnamed: 0   a   b   c   d
0             0           0   0   1   2   3
1             1           1   4   5   6   7
2             2           2   8   9  10  11
3             3           3  12  13  14  15

In [ ]:
# We are reading the HTML data from website.
data = pd.read_html(r'https://www.fdic.gov/bank/individual/failed/banklist.html')

In [ ]:
#By default the data is in list format.
type(data)

list

In [55]:
#As we see above the data was stored in the list format, now we need to access the data in list way.
data[0].head()

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Tioga-Franklin Savings Bank,Philadelphia,Pennsylvania,33802,Second Federal Savings and Loan Association of...,"August 21, 2026",10554
1,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
2,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
3,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
4,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550

- For above HTML list data we need to convert it to pandas dataframe.
- Then we need to save as any format.

#### ```Working with SQLALCHEMY```

In [ ]:
# It allow us to create a simple SQL environment in memory.
from sqlalchemy import create_engine

In [66]:
#We are creating a environment in memory to do our processing.
engine = create_engine('sqlite:///:memory:')

In [67]:
#We are writing to sql from our dataframe and give connection to memory.
df.to_sql('my_table', engine, index=False)

4

In [68]:
sqldf = pd.read_sql('my_table',con=engine)
sqldf

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15